@startuml BotState
Title State bot?

Initialization : Enrty / LoadConfig
Initialization : Connect / Connection

[*] --> Initialization

Initialization --> WaitingCommand : Init / Configure
WaitingCommand --> ProcessTask : Input / CreateTask
WaitingCommand --> ProcessTask : Input / Status
SendStatusResult --> WaitingCommand : StatusSended
ProcessTask --> CheckTask : SendTaskStatus
CheckTask --> SendStatusResult : GetTaskStatus
ProcessTask --> CreateTask : Creation / Create
CreateTask --> ProcessTask : Created
UpdateStatus --> ProcessTask : Completed
ProcessTask --> WaitingCommand : Completed
ProcessTask --> UpdateStatus : Finded / Complete
ProcessTask --> UpdateStatus : NotFinded / Complete
ProcessTask --> PollingExecutor : Created / Start polling

WaitingCommand --> Exit : Exit
Exit --> [*]

@enduml
