@startuml Components
    Title Components

    package "Presenter"{
        [Input]
        [Output]
    }

    package "Logic"{
        [IInput]
        [IOutput]
        [CommandParser]
        [IExecutorFinder]
        [IStorage]
        [ObjectiveProcessor]
    }

    package "Infrastructure"{
        [Storage]
    }

    package "ExecutorFinder"{
        [ChannelMessage]
        [PersonalMessage]
        [AssignAlgorithm]
    }

    [Input] --|> [IInput]
    [Output] --|> [IOutput]

    [IInput] --> [CommandParser] 
    [IOutput] --> [CommandParser]
    [CommandParser] --> [ObjectiveProcessor]
    [IExecutorFinder] --> [ObjectiveProcessor]
    [IStorage] --> [ObjectiveProcessor]
    

    [ChannelMessage] --|> [IExecutorFinder]
    [PersonalMessage] --|> [IExecutorFinder]
    [AssignAlgorithm] --|> [IExecutorFinder]

    [Storage] --|> [IStorage]
@enduml