@startuml UseCase
    Title Usecase
    left to right direction

    actor ObjectiveProducer
    actor ObjectiveExecutor
    actor Bot
    
    rectangle {
        usecase FindExecutor
        usecase CreateObjective
        usecase AssignIdentificator
        usecase RequestStatus
        usecase GetObjective
        usecase NotifyStatus
    }

    ObjectiveProducer -- CreateObjective
    Bot -- CreateObjective
    ObjectiveExecutor -- GetObjective
    Bot -- FindExecutor 
    Bot -- NotifyStatus
    ObjectiveProducer -- RequestStatus
    RequestStatus --> NotifyStatus : include
    FindExecutor -- ObjectiveExecutor
    Bot -- AssignIdentificator

@endmul