@startuml UseCase
    Title Usecase
    left to right direction

    actor "Objective Producer" as ObjectiveProducer
    actor "Objective Executor" as ObjectiveExecutor
    actor Bot
    
    rectangle {
        usecase "Find Executor" as FindExecutor
        usecase "Create Objective" as CreateObjective
        usecase "Assign Identificator" as AssignIdentificator
        usecase "Request Status" as RequestStatus
        usecase "Get Objective" as GetObjective
        usecase "Notify Status" as NotifyStatus
    }

    ObjectiveProducer -- CreateObjective
    Bot -- CreateObjective
    ObjectiveExecutor -- GetObjective
    Bot -- FindExecutor 
    Bot -- NotifyStatus
    ObjectiveProducer -- RequestStatus
    RequestStatus --> NotifyStatus : include
    FindExecutor -- ObjectiveExecutor
    Bot -- AssignIdentificator

@endmul